# Generated by Django 4.1.2 on 2022-11-25 13:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        CreateExtension('postgis'),
        CreateExtension('postgis_raster'),
        migrations.CreateModel(
            name="Park",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Название парка",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                ("address", models.CharField(max_length=150)),
                (
                    "description",
                    models.TextField(
                        help_text="Описание парка",
                        max_length=500,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "geofence",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
            ],
            options={
                "db_table": "parks",
            },
        ),
    ]
